export ALIEN_JDL_LPMANCHORPASSNAME=apass7
export ALIEN_JDL_MCANCHOR=apass7
export ALIEN_JDL_COLLISIONSYSTEM=pp 
export ALIEN_JDL_CPULIMIT=60 
export ALIEN_JDL_LPMPASSNAME=apass7
export ALIEN_JDL_LPMRUNNUMBER=523559
export ALIEN_JDL_LPMPRODUCTIONTYPE=MC 
export ALIEN_JDL_LPMINTERACTIONTYPE=pp 
export ALIEN_JDL_LPMPRODUCTIONTAG=LHC24f3b
export ALIEN_JDL_LPMANCHORRUN=523559
export ALIEN_JDL_LPMANCHORPRODUCTION=LHC24f3b
export ALIEN_JDL_LPMANCHORYEAR=2022
export NSIGEVENTS=10
export NBKGEVENTS=10
export DISABLE_QC=1
export ALIEN_JDL_ANCHOR_SIM_OPTIONS="-gen pythia8 -genBkg pythia8 -procBkg pp -colBkg pp -nb ${NBKGEVENTS} -ns ${NSIGEVENTS} -ini ${O2DPG}/MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2.ini"


export NTIMEFRAMES=2 #?
export SPLITID=100  #?
export PRODSPLIT=153 #?
export CYCLE=0 #?
export ALIEN_PROC_ID=2963436952 #?


${O2DPG_ROOT}/MC/run/ANCHOR/anchorMC.sh