#!/bin/bash

export ALIEN_JDL_LPMANCHORPASSNAME="apass1"
export ALIEN_JDL_MCANCHOR="apass1"
export ALIEN_JDL_CPULIMIT=8
export ALIEN_JDL_LPMPASSNAME="apass1"
export ALIEN_JDL_LPMRUNNUMBER="559456"
export ALIEN_JDL_LPMPRODUCTIONTYPE=MC
export ALIEN_JDL_LPMINTERACTIONTYPE="pp"
export ALIEN_JDL_COLLISIONSYSTEM="pp"
export ALIEN_JDL_LPMPRODUCTIONTAG="test_anchor_2024_apass1_ppref_2tag"
export ALIEN_JDL_LPMANCHORRUN="559456"
export ALIEN_JDL_LPMANCHORPRODUCTION="LHC25b4b4"
export ALIEN_JDL_LPMANCHORYEAR="2024"

export NTIMEFRAMES=4
export NSIGEVENTS=100
export SPLITID=100
export PRODSPLIT=3351
export CYCLE=0
# disable the QC
export DISABLE_QC=1

export O2DPG_MC_CONFIG_ROOT="/cvmfs/alice.cern.ch/el9-x86_64/Packages/O2DPG/daily-20250701-0000-1"
INI_PATH=${O2DPG_MC_CONFIG_ROOT}/MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_Mode2_pp_ref.ini

export ALIEN_JDL_ANCHOR_SIM_OPTIONS="-gen external -ini $INI_PATH"

${O2DPG_ROOT}/MC/run/ANCHOR/anchorMC.sh